M48
; DRILL file {KiCad (6.0.11)} date Wed Mar  1 16:43:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-01T16:43:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X6.5575Y-2.9475
X6.5575Y-4.5725
X7.4325Y-2.9475
X7.4325Y-4.5725
T0
M30
